# Generated by Django 4.1 on 2022-08-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
